;;; macher-agent-test-setup.el --- Shared Setup for Macher-Agent Tests -*- lexical-binding: t; -*-

(let* ((this-file (or load-file-name buffer-file-name))
       (this-dir (if this-file
                     (file-name-directory (expand-file-name this-file))
                   (expand-file-name default-directory)))
       (root-dir (or (locate-dominating-file this-dir "macher-agent.el")
                     (let ((d (locate-dominating-file this-dir "tests")))
                       (and d (expand-file-name d)))
                     (and (file-exists-p (expand-file-name "macher-agent.el" this-dir))
                          this-dir)
                     (and (file-exists-p (expand-file-name "macher-agent.el" (expand-file-name ".." this-dir)))
                          (file-name-as-directory (expand-file-name ".." this-dir)))
                     this-dir))
       (test-dir (or (and (file-exists-p (expand-file-name "macher-agent-test-setup.el" this-dir))
                          this-dir)
                     (and (file-exists-p (expand-file-name "tests/macher-agent-test-setup.el" root-dir))
                          (expand-file-name "tests" root-dir))
                     (and (file-directory-p (expand-file-name "tests" root-dir))
                          (expand-file-name "tests" root-dir))
                     this-dir))
       (helpers-dir (or (and (file-directory-p (expand-file-name "helpers" test-dir))
                             (expand-file-name "helpers" test-dir))
                        (and (file-directory-p (expand-file-name "tests/helpers" root-dir))
                             (expand-file-name "tests/helpers" root-dir))
                        (expand-file-name "helpers" test-dir))))
  (when (and root-dir (file-directory-p root-dir))
    (add-to-list 'load-path (file-name-as-directory (expand-file-name root-dir)))
    (let ((macher-dir (expand-file-name "macher" root-dir)))
      (when (file-directory-p macher-dir)
        (add-to-list 'load-path (file-name-as-directory macher-dir))))
    (let ((gptel-dir (expand-file-name "gptel" root-dir)))
      (when (file-directory-p gptel-dir)
        (add-to-list 'load-path (file-name-as-directory gptel-dir))))
    (let ((skills-dir (expand-file-name "skills/scripts" root-dir)))
      (when (file-directory-p skills-dir)
        (add-to-list 'load-path (file-name-as-directory skills-dir)))))
  (add-to-list 'load-path (expand-file-name "tests" default-directory))
  (add-to-list 'load-path (file-name-directory (or load-file-name (buffer-file-name) default-directory)))
  (add-to-list 'load-path (expand-file-name "helpers" (file-name-directory (or load-file-name (buffer-file-name) default-directory))))
  (when (and test-dir (file-directory-p test-dir))
    (add-to-list 'load-path (file-name-as-directory (expand-file-name test-dir))))
  (when (and helpers-dir (file-directory-p helpers-dir))
    (add-to-list 'load-path (file-name-as-directory (expand-file-name helpers-dir)))))

(require 'subr-x)
(require 'buttercup)
(require 'cl-lib)
(require 'macher nil t)
(unless (fboundp 'macher--make-context)
  (cl-defstruct (macher-context (:constructor macher--make-context))
    contents
    workspace
    prompt
    process-request-function
    data
    dirty-p
    shadow-buffers))
(require 'macher-agent-core)
(require 'macher-agent-gptel)
(require 'macher-agent-presets)
(require 'macher-agent-tools)
(require 'macher-agent-sandbox)
(require 'macher-agent-vfs)
(require 'macher-agent-zero-mem)
(require 'macher-agent-orchestration)
(require 'macher-agent-api)
(require 'macher-agent)
(require 'macher-agent-test-harness)
(require 'macher-agent-snippet-extractor)

(defvar gptel--fsm)
(defvar macher-agent--active-fsm)
(defvar gptel--fsm-last)

(unless (fboundp 'make-gptel-fsm)
  (if (fboundp 'gptel-make-fsm)
      (defalias 'make-gptel-fsm #'gptel-make-fsm)
    (defun make-gptel-fsm (&rest args)
      (if (plist-member args :info) args (list :info args)))))

(when (fboundp 'macher-agent-install)
  (macher-agent-install))
(when (fboundp 'macher-agent-context-resolution-install)
  (macher-agent-context-resolution-install))
(setq macher-agent-search-backend-function #'macher-agent-search-glob)

(defmacro macher-agent-test-setup-before-each ()
  `(before-each
    (spy-on 'macher-action)
    (spy-on 'gptel-send)
    (spy-on 'macher--add-termination-handler)
    (setq macher-agent--persistent-context nil)
    (setq macher-agent-search-backend-function #'macher-agent-search-glob)
    (when (and (boundp 'macher-agent--pending-callbacks) (hash-table-p macher-agent--pending-callbacks))
      (clrhash macher-agent--pending-callbacks))
    (when (and (boundp 'macher-agent--task-registry) (hash-table-p macher-agent--task-registry))
      (clrhash macher-agent--task-registry))
    (when (and (boundp 'macher-agent--a2a-ownership) (hash-table-p macher-agent--a2a-ownership))
      (clrhash macher-agent--a2a-ownership))
    (let* ((ctx (ignore-errors (macher-agent-context-from-buffer (current-buffer))))
           (ws (when ctx (macher-agent-context-workspace ctx))))
      (when ws (setf (macher-agent-workspace-active-subagents ws) nil)))))

(provide 'macher-agent-test-setup)
;;; macher-agent-test-setup.el ends here
